name: Create AUR Release
description: Create a AUR release on version bump
author: ATiltedTree
branding:
  color: green
  icon: upload
inputs:
  package_name:
    description: The name of the AUR package to update.
    required: true
  package_version:
    description: The version of the AUR package to publish.
    required: false
    default: ${{ github.ref_name }}
  commit_username:
    description: The username to use when creating the new commit.
    required: true
  commit_email:
    description: The email to use when creating the new commit.
    required: true
  ssh_private_key:
    description: The SSH private key with access to the specified AUR package.
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.package_name }} ${{ inputs.package_version }} ${{ inputs.commit_username }} ${{ inputs.commit_email }} ${{ inputs.ssh_private_key }}
